apiVersion: net.techonfire.ir/v1alpha1
kind: IPPoolPolicy
metadata:
  name: arvan-edge-ingress
spec:
  refreshInterval: 30m
  source:
    urls:
      - https://www.arvancloud.ir/en/ips.txt
  target:
    namespaceSelector:
      matchLabels:
        enforce-ip-allowlist: "true"
    podSelector:
      matchLabels:
        app: nginx
  policy:
    types: [Ingress]
    namePrefix: ippool-
    ports:
      - port: 443
        protocol: TCP
      - port: 80
        protocol: TCP
